Tests for encoding of macro parameters
reszelaz/sardana pull request #6
Opened 2017-02-13 15:34 UTC by sagiss

Insert tests to check the correct encoding/decoding of macro
parameters.

Using insertTest decorator, different parameter combinations
(including repeat parameters) are tested.

2017-02-15 07:19 UTC, reszelaz requested changes

2017-02-15 07:19 UTC, reszelaz commented on src/sardana/taurus/core/tango/sardana/test/res/params_definitions.py
> +params_definition_move = [
I would reference in the variable names with the macro examples located in `sardana.macroserver.macros.examples.parameters`. So `pt0_param_def`, `pt01_param_def`, ...

2017-02-15 07:19 UTC, reszelaz commented on src/sardana/taurus/core/tango/sardana/test/res/params_definitions.py
> +params_definition_move = [
Apart of that I would make a dedicated module called: `paramdef` where I would place all these definitions together with the one already defined in `test_macro` module.

2017-02-15 07:19 UTC, reszelaz commented on src/sardana/taurus/core/tango/sardana/test/res/params_definitions.py
> +move_parameters_1 = [[["mot01", "0"]]]
Personally I would keep the parameter values close to the `insertTest` calls so in the test module. I think that we will gain the readability. But treat is just as a suggestion.

2017-02-15 07:19 UTC, reszelaz commented on src/sardana/taurus/core/tango/sardana/test/test_macro_paramrepeat.py
> +#!/usr/bin/env python
I would merge this module with the already existing one `test_macro`.

2017-02-15 11:50 UTC, sagiss commented on src/sardana/taurus/core/tango/sardana/test/res/params_definitions.py
> +params_definition_move = [
Done

2017-02-15 11:51 UTC, sagiss commented on src/sardana/taurus/core/tango/sardana/test/res/params_definitions.py
> +move_parameters_1 = [[["mot01", "0"]]]
Done

2017-02-15 11:51 UTC, sagiss commented on src/sardana/taurus/core/tango/sardana/test/test_macro_paramrepeat.py
> +#!/usr/bin/env python
Done

2017-02-16 10:54 UTC, reszelaz approved these changes

2017-02-16 10:54 UTC, merged